// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PUSHApplication.DAL;

namespace PUSHApplication.DAL.Migrations
{
    [DbContext(typeof(PUSHApplicationContext))]
    partial class PUSHApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PUSHApplication.DAL.Models.Message", b =>
                {
                    b.Property<long>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Header")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MessageSendTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MessageId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("PUSHApplication.DAL.Models.MessageToPhoneNumber", b =>
                {
                    b.Property<long>("MessageId")
                        .HasColumnType("bigint");

                    b.Property<string>("MobileAppPhoneNumber")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MessageId", "MobileAppPhoneNumber");

                    b.HasIndex("MobileAppPhoneNumber");

                    b.ToTable("MessageToPhoneNumbers");
                });

            modelBuilder.Entity("PUSHApplication.DAL.Models.MobileApp", b =>
                {
                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AppVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirebaseToken")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PhoneNumber");

                    b.HasIndex("PhoneNumber");

                    b.ToTable("MobileApps");
                });

            modelBuilder.Entity("PUSHApplication.DAL.Models.MessageToPhoneNumber", b =>
                {
                    b.HasOne("PUSHApplication.DAL.Models.Message", "Message")
                        .WithMany("MessageToPhoneNumbers")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PUSHApplication.DAL.Models.MobileApp", "MobileApp")
                        .WithMany("MessageToPhoneNumbers")
                        .HasForeignKey("MobileAppPhoneNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");

                    b.Navigation("MobileApp");
                });

            modelBuilder.Entity("PUSHApplication.DAL.Models.Message", b =>
                {
                    b.Navigation("MessageToPhoneNumbers");
                });

            modelBuilder.Entity("PUSHApplication.DAL.Models.MobileApp", b =>
                {
                    b.Navigation("MessageToPhoneNumbers");
                });
#pragma warning restore 612, 618
        }
    }
}
